### ISSUE TITLE
Menu doesn't load: Uncaught SyntaxError: expected expression, got '=>'

### ISSUE THREAD

**Issue by jdlrobson** [morags/mediawiki-2018-skin#7]
ResourceLoader (what Mediawiki uses to ship JS with) doesn't support ES6 syntax in its JS minifier as it stands (If I recall correctly).

This means the skin only works with debug=true appended to the URI

The skin likely make use of webpack or some other bundler to create a single ES5 compatible JavaScript build to ship its JS assets. 

Note: Given version numbers in package.json are inconsistent, I can't consistently reproduce this. Skin works fine on my local build but not on my deployed build :/

Note 2: The inclusion of jQuery seems unnecessary - all skins should have this available by default so right now it loads jquery twice.

**Comment by morags** [comment]
Thanks. I've Babel-ized everything at 7f27f1115574181fcf1b63e5afb752d0f8e00829, so that should be resolved. I am having some trouble with the JS, though - the `load` event doesn't always fire, so the content transformations aren't being executed.

Removing jQuery from skin.json results in `$.fn is undefined` errors...

**Comment by jdlrobson** [comment]
Yeh that seems to do it.

As for the jQuery issue, you'll need to drop node_modules/tablesorter/dist/js/jquery.tablesorter.js to avoid the $.fn is undefined errors.. Note we already load jquery tablesorter for all skins, so this code should be redundant anyway if that's the only reason it's been loaded!
